### ISSUE TITLE
TimestampUrl is an invalid URL when this argument is empty

### ISSUE THREAD

**Issue by dvoituron** [mansellan/clickonce#32]
Hello... Thanks for this greate AzureDevOps extension.

I've a problem when using a certificate with a `Thumbprint`, but without `Timestamp URL`.
I've received an error **Error setting value to option 'timestampurl': Invalid URI: The format of the URI could not be determined.** because the argument **--timestampUrl** is set.

Can you remove this parameter if the **timestampUrl** is empty?

Thanks

Find here the Yaml used.

```yaml
steps:
- task: mansellan.clickonce.clickonce-task.clickonce@1
  displayName: 'ClickOnce Package'
  inputs:
    source: '$(System.DefaultWorkingDirectory)/drop'
    target: '$(System.DefaultWorkingDirectory)/Publish'
    product: 'MyProduct'
    version: '$(Build.BuildNumber)'
    publisher: MyCompany
    createDesktopShortcut: true
    deploymentUrl: 'https://mywebsite.net/'
    targetFramework: net48
    prerequisitesMode: vendor
    prerequisite1: '.NETFramework,Version=v4.8'
    signingMode: installed
    thumbprint: 84599cec4d8b0d567b819a3eb75a100749b8f155
    verbosity: verbose 
```
